import type { Member, Plan, Dish } from '../../shared/types.js';

export const mockMembers: Member[] = [
  {
    id: 'm1',
    name: '张三',
    phone: '13800138001',
    allergies: ['seafood'],
    religiousDiet: '',
    drinksAlcohol: true,
    notes: '海鲜过敏严重',
    confirmed: true,
    createdAt: '2026-06-01T10:00:00Z',
  },
  {
    id: 'm2',
    name: '李四',
    phone: '13800138002',
    allergies: ['nuts', 'spicy'],
    religiousDiet: 'vegetarian',
    drinksAlcohol: false,
    notes: '素食主义者，坚果过敏',
    confirmed: true,
    createdAt: '2026-06-01T10:01:00Z',
  },
  {
    id: 'm3',
    name: '王五',
    phone: '13800138003',
    allergies: [],
    religiousDiet: 'halal',
    drinksAlcohol: true,
    notes: '清真',
    confirmed: false,
    createdAt: '2026-06-01T10:02:00Z',
  },
  {
    id: 'm4',
    name: '赵六',
    phone: '13800138004',
    allergies: ['spicy'],
    religiousDiet: '',
    drinksAlcohol: true,
    notes: '不能吃辣',
    confirmed: true,
    createdAt: '2026-06-01T10:03:00Z',
  },
  {
    id: 'm5',
    name: '钱七',
    phone: '13800138005',
    allergies: ['dairy'],
    religiousDiet: '',
    drinksAlcohol: false,
    notes: '乳糖不耐受',
    confirmed: true,
    createdAt: '2026-06-01T10:04:00Z',
  },
  {
    id: 'm6',
    name: '孙八',
    phone: '13800138006',
    allergies: [],
    religiousDiet: '',
    drinksAlcohol: true,
    notes: '',
    confirmed: false,
    createdAt: '2026-06-01T10:05:00Z',
  },
  {
    id: 'm7',
    name: '周九',
    phone: '13800138007',
    allergies: ['seafood', 'nuts'],
    religiousDiet: '',
    drinksAlcohol: true,
    notes: '海鲜和坚果都过敏',
    confirmed: true,
    createdAt: '2026-06-01T10:06:00Z',
  },
  {
    id: 'm8',
    name: '吴十',
    phone: '13800138008',
    allergies: [],
    religiousDiet: 'vegetarian',
    drinksAlcohol: false,
    notes: '素食',
    confirmed: true,
    createdAt: '2026-06-01T10:07:00Z',
  },
  {
    id: 'm9',
    name: '郑十一',
    phone: '13800138009',
    allergies: ['gluten'],
    religiousDiet: '',
    drinksAlcohol: true,
    notes: '麸质过敏',
    confirmed: true,
    createdAt: '2026-06-01T10:08:00Z',
  },
  {
    id: 'm10',
    name: '陈十二',
    phone: '13800138010',
    allergies: [],
    religiousDiet: '',
    drinksAlcohol: false,
    notes: '备孕中，不喝酒',
    confirmed: true,
    createdAt: '2026-06-01T10:09:00Z',
  },
  {
    id: 'm11',
    name: '林十三',
    phone: '13800138011',
    allergies: ['spicy', 'seafood'],
    religiousDiet: '',
    drinksAlcohol: true,
    notes: '不吃辣不吃海鲜',
    confirmed: false,
    createdAt: '2026-06-01T10:10:00Z',
  },
  {
    id: 'm12',
    name: '黄十四',
    phone: '13800138012',
    allergies: [],
    religiousDiet: 'halal',
    drinksAlcohol: false,
    notes: '清真，不喝酒',
    confirmed: true,
    createdAt: '2026-06-01T10:11:00Z',
  },
];

const mockDishes: Dish[] = [
  {
    id: 'd1',
    name: '清蒸鲈鱼',
    spiciness: 'none',
    hasSeafood: true,
    hasNuts: false,
    isVegetarian: false,
    price: 128,
    notes: '招牌菜',
  },
  {
    id: 'd2',
    name: '宫保鸡丁',
    spiciness: 'medium',
    hasSeafood: false,
    hasNuts: true,
    isVegetarian: false,
    price: 58,
    notes: '含花生',
  },
  {
    id: 'd3',
    name: '麻婆豆腐',
    spiciness: 'hot',
    hasSeafood: false,
    hasNuts: false,
    isVegetarian: true,
    price: 38,
    notes: '辣味',
  },
  {
    id: 'd4',
    name: '白灼菜心',
    spiciness: 'none',
    hasSeafood: false,
    hasNuts: false,
    isVegetarian: true,
    price: 28,
    notes: '清淡',
  },
  {
    id: 'd5',
    name: '蒜蓉粉丝蒸虾',
    spiciness: 'none',
    hasSeafood: true,
    hasNuts: false,
    isVegetarian: false,
    price: 88,
    notes: '海鲜',
  },
  {
    id: 'd6',
    name: '腰果西芹',
    spiciness: 'none',
    hasSeafood: false,
    hasNuts: true,
    isVegetarian: true,
    price: 42,
    notes: '素食，含腰果',
  },
  {
    id: 'd7',
    name: '红烧肉',
    spiciness: 'none',
    hasSeafood: false,
    hasNuts: false,
    isVegetarian: false,
    price: 68,
    notes: '经典',
  },
  {
    id: 'd8',
    name: '水煮鱼',
    spiciness: 'hot',
    hasSeafood: true,
    hasNuts: false,
    isVegetarian: false,
    price: 98,
    notes: '麻辣，海鲜',
  },
  {
    id: 'd9',
    name: '凉拌木耳',
    spiciness: 'mild',
    hasSeafood: false,
    hasNuts: false,
    isVegetarian: true,
    price: 22,
    notes: '微辣',
  },
  {
    id: 'd10',
    name: '烤羊排',
    spiciness: 'medium',
    hasSeafood: false,
    hasNuts: false,
    isVegetarian: false,
    price: 168,
    notes: '非清真',
  },
];

export const mockPlans: Plan[] = [
  {
    id: 'p1',
    name: '2026年中团建聚餐',
    restaurant: '大香港酒楼',
    date: '2026-06-28',
    totalTables: 2,
    seatsPerTable: 6,
    dishes: mockDishes,
    drinks: {
      alcoholic: ['青岛啤酒', '长城干红', '茅台'],
      nonAlcoholic: ['可乐', '雪碧', '鲜榨橙汁', '矿泉水'],
    },
    budget: 3000,
    createdAt: '2026-06-01T09:00:00Z',
  },
];

export async function initializeMockData(): Promise<void> {
  const { writeJsonFile, readJsonFile } = await import('./jsonFileStorage.js');
  
  const existingMembers = await readJsonFile<Member[]>('members.json');
  if (existingMembers.length === 0) {
    await writeJsonFile('members.json', mockMembers);
  }
  
  const existingPlans = await readJsonFile<Plan[]>('plans.json');
  if (existingPlans.length === 0) {
    await writeJsonFile('plans.json', mockPlans);
  }
}
