import { addDays, format } from 'date-fns';
import type { Subscription } from '@/types';

const today = new Date();

export const mockSubscriptions: Subscription[] = [
  {
    id: 'sub-001',
    name: 'Netflix 高级',
    purpose: '看剧、电影',
    category: 'entertainment',
    channel: 'credit_card',
    billingCycle: 'monthly',
    amount: 98,
    currency: 'CNY',
    nextBillingDate: format(addDays(today, 2), 'yyyy-MM-dd'),
    lastBillingDate: format(addDays(today, -28), 'yyyy-MM-dd'),
    logoEmoji: '🎥',
    familyMembers: ['老婆', '弟弟'],
    isTrial: false,
    isPriceIncreased: true,
    priceHistory: [{ date: '2026-01-15', from: 78, to: 98 }],
    cardFailCount: 0,
    lastConfirmedAt: format(addDays(today, -100), 'yyyy-MM-dd\'T\'HH:mm:ss'),
    createdAt: '2025-06-15T10:00:00',
    updatedAt: format(today, 'yyyy-MM-dd\'T\'HH:mm:ss'),
    notes: '4K HDR 全家共享',
  },
  {
    id: 'sub-002',
    name: 'Spotify 家庭版',
    purpose: '听音乐、播客',
    category: 'entertainment',
    channel: 'appstore',
    billingCycle: 'monthly',
    amount: 58,
    currency: 'CNY',
    nextBillingDate: format(addDays(today, 5), 'yyyy-MM-dd'),
    lastBillingDate: format(addDays(today, -25), 'yyyy-MM-dd'),
    logoEmoji: '🎵',
    familyMembers: ['全家'],
    isTrial: false,
    isPriceIncreased: false,
    priceHistory: [],
    cardFailCount: 0,
    lastConfirmedAt: format(addDays(today, -45), 'yyyy-MM-dd\'T\'HH:mm:ss'),
    createdAt: '2025-03-01T10:00:00',
    updatedAt: format(today, 'yyyy-MM-dd\'T\'HH:mm:ss'),
  },
  {
    id: 'sub-003',
    name: '得到会员',
    purpose: '听书、课程学习',
    category: 'education',
    channel: 'alipay',
    billingCycle: 'yearly',
    amount: 365,
    currency: 'CNY',
    nextBillingDate: format(addDays(today, 45), 'yyyy-MM-dd'),
    lastBillingDate: format(addDays(today, -320), 'yyyy-MM-dd'),
    logoEmoji: '📖',
    familyMembers: [],
    isTrial: false,
    isPriceIncreased: false,
    priceHistory: [],
    cardFailCount: 1,
    lastConfirmedAt: format(addDays(today, -20), 'yyyy-MM-dd\'T\'HH:mm:ss'),
    createdAt: '2024-08-01T10:00:00',
    updatedAt: format(today, 'yyyy-MM-dd\'T\'HH:mm:ss'),
  },
  {
    id: 'sub-004',
    name: 'Notion AI',
    purpose: '笔记、知识库、AI写作',
    category: 'office',
    channel: 'credit_card',
    billingCycle: 'monthly',
    amount: 72,
    currency: 'CNY',
    nextBillingDate: format(addDays(today, 12), 'yyyy-MM-dd'),
    lastBillingDate: format(addDays(today, -18), 'yyyy-MM-dd'),
    logoEmoji: '📝',
    familyMembers: [],
    isTrial: true,
    trialEndDate: format(addDays(today, 3), 'yyyy-MM-dd'),
    trialReminderDays: 3,
    isPriceIncreased: false,
    priceHistory: [],
    cardFailCount: 0,
    lastConfirmedAt: format(addDays(today, -5), 'yyyy-MM-dd\'T\'HH:mm:ss'),
    createdAt: format(addDays(today, -20), 'yyyy-MM-dd\'T\'HH:mm:ss'),
    updatedAt: format(today, 'yyyy-MM-dd\'T\'HH:mm:ss'),
    notes: '7天试用，到期前需评估',
  },
  {
    id: 'sub-005',
    name: 'Figma Pro',
    purpose: 'UI设计协作',
    category: 'office',
    channel: 'paypal',
    billingCycle: 'monthly',
    amount: 108,
    currency: 'CNY',
    nextBillingDate: format(addDays(today, 8), 'yyyy-MM-dd'),
    lastBillingDate: format(addDays(today, -22), 'yyyy-MM-dd'),
    logoEmoji: '🎨',
    familyMembers: [],
    isTrial: false,
    isPriceIncreased: false,
    priceHistory: [],
    cardFailCount: 0,
    lastConfirmedAt: format(addDays(today, -15), 'yyyy-MM-dd\'T\'HH:mm:ss'),
    createdAt: '2025-01-10T10:00:00',
    updatedAt: format(today, 'yyyy-MM-dd\'T\'HH:mm:ss'),
  },
  {
    id: 'sub-006',
    name: 'iCloud+ 200GB',
    purpose: '家庭照片备份、同步',
    category: 'family',
    channel: 'appstore',
    billingCycle: 'monthly',
    amount: 21,
    currency: 'CNY',
    nextBillingDate: format(addDays(today, 1), 'yyyy-MM-dd'),
    lastBillingDate: format(addDays(today, -29), 'yyyy-MM-dd'),
    logoEmoji: '☁️',
    familyMembers: ['老婆', '爸妈'],
    isTrial: false,
    isPriceIncreased: false,
    priceHistory: [],
    cardFailCount: 0,
    lastConfirmedAt: format(addDays(today, -60), 'yyyy-MM-dd\'T\'HH:mm:ss'),
    createdAt: '2024-12-01T10:00:00',
    updatedAt: format(today, 'yyyy-MM-dd\'T\'HH:mm:ss'),
  },
  {
    id: 'sub-007',
    name: '京东PLUS',
    purpose: '购物优惠、免运费',
    category: 'family',
    channel: 'wechat',
    billingCycle: 'yearly',
    amount: 198,
    currency: 'CNY',
    nextBillingDate: format(addDays(today, 68), 'yyyy-MM-dd'),
    lastBillingDate: format(addDays(today, -297), 'yyyy-MM-dd'),
    logoEmoji: '🛒',
    familyMembers: ['老婆'],
    isTrial: false,
    isPriceIncreased: false,
    priceHistory: [],
    cardFailCount: 0,
    lastConfirmedAt: format(addDays(today, -30), 'yyyy-MM-dd\'T\'HH:mm:ss'),
    createdAt: '2024-08-15T10:00:00',
    updatedAt: format(today, 'yyyy-MM-dd\'T\'HH:mm:ss'),
  },
  {
    id: 'sub-008',
    name: '爱奇艺黄金VIP',
    purpose: '追剧',
    category: 'entertainment',
    channel: 'alipay',
    billingCycle: 'quarterly',
    amount: 78,
    currency: 'CNY',
    nextBillingDate: format(addDays(today, 20), 'yyyy-MM-dd'),
    lastBillingDate: format(addDays(today, -70), 'yyyy-MM-dd'),
    logoEmoji: '📺',
    familyMembers: [],
    isTrial: false,
    isPriceIncreased: false,
    priceHistory: [],
    cardFailCount: 0,
    duplicateOfId: 'sub-001',
    lastConfirmedAt: format(addDays(today, -110), 'yyyy-MM-dd\'T\'HH:mm:ss'),
    createdAt: '2025-02-01T10:00:00',
    updatedAt: format(today, 'yyyy-MM-dd\'T\'HH:mm:ss'),
    notes: '和Netflix有点重复？',
  },
  {
    id: 'sub-009',
    name: 'GitHub Copilot',
    purpose: 'AI代码助手',
    category: 'office',
    channel: 'credit_card',
    billingCycle: 'monthly',
    amount: 70,
    currency: 'CNY',
    nextBillingDate: format(addDays(today, 15), 'yyyy-MM-dd'),
    lastBillingDate: format(addDays(today, -15), 'yyyy-MM-dd'),
    logoEmoji: '🤖',
    familyMembers: [],
    isTrial: false,
    isPriceIncreased: true,
    priceHistory: [{ date: '2026-04-01', from: 56, to: 70 }],
    cardFailCount: 0,
    lastConfirmedAt: format(addDays(today, -10), 'yyyy-MM-dd\'T\'HH:mm:ss'),
    createdAt: '2025-05-01T10:00:00',
    updatedAt: format(today, 'yyyy-MM-dd\'T\'HH:mm:ss'),
  },
  {
    id: 'sub-010',
    name: 'Apple Fitness+',
    purpose: '健身课程',
    category: 'family',
    channel: 'appstore',
    billingCycle: 'monthly',
    amount: 28,
    currency: 'CNY',
    nextBillingDate: format(addDays(today, 22), 'yyyy-MM-dd'),
    lastBillingDate: format(addDays(today, -8), 'yyyy-MM-dd'),
    logoEmoji: '🏋️',
    familyMembers: ['全家'],
    isTrial: false,
    isPriceIncreased: false,
    priceHistory: [],
    cardFailCount: 0,
    lastConfirmedAt: format(addDays(today, -5), 'yyyy-MM-dd\'T\'HH:mm:ss'),
    createdAt: '2025-09-01T10:00:00',
    updatedAt: format(today, 'yyyy-MM-dd\'T\'HH:mm:ss'),
  },
];
