import { ElementType } from './index'
import type { ComponentDef } from './index'

export const COMPONENT_DEFS: ComponentDef[] = [
  {
    type: ElementType.RECT,
    label: 'Rectangle',
    category: 'basic',
    defaultWidth: 120,
    defaultHeight: 80,
    defaultProps: { fill: '#ffffff', stroke: '#333333' },
  },
  {
    type: ElementType.CIRCLE,
    label: 'Circle',
    category: 'basic',
    defaultWidth: 80,
    defaultHeight: 80,
    defaultProps: { fill: '#ffffff', stroke: '#333333' },
  },
  {
    type: ElementType.TRIANGLE,
    label: 'Triangle',
    category: 'basic',
    defaultWidth: 100,
    defaultHeight: 90,
    defaultProps: { fill: '#ffffff', stroke: '#333333' },
  },
  {
    type: ElementType.LINE,
    label: 'Line',
    category: 'basic',
    defaultWidth: 150,
    defaultHeight: 2,
    defaultProps: { fill: 'transparent', stroke: '#333333', strokeWidth: 2 },
  },
  {
    type: ElementType.INPUT,
    label: 'Input',
    category: 'form',
    defaultWidth: 200,
    defaultHeight: 36,
    defaultProps: { fill: '#ffffff', stroke: '#cccccc', text: 'Input', cornerRadius: 4 },
  },
  {
    type: ElementType.BUTTON,
    label: 'Button',
    category: 'form',
    defaultWidth: 120,
    defaultHeight: 36,
    defaultProps: { fill: '#4A90D9', stroke: '#3A7BC8', text: 'Button', cornerRadius: 4 },
  },
  {
    type: ElementType.DROPDOWN,
    label: 'Dropdown',
    category: 'form',
    defaultWidth: 200,
    defaultHeight: 36,
    defaultProps: { fill: '#ffffff', stroke: '#cccccc', text: 'Select...', cornerRadius: 4 },
  },
  {
    type: ElementType.CHECKBOX,
    label: 'Checkbox',
    category: 'form',
    defaultWidth: 20,
    defaultHeight: 20,
    defaultProps: { fill: '#ffffff', stroke: '#333333' },
  },
  {
    type: ElementType.RADIO,
    label: 'Radio',
    category: 'form',
    defaultWidth: 20,
    defaultHeight: 20,
    defaultProps: { fill: '#ffffff', stroke: '#333333' },
  },
  {
    type: ElementType.SWITCH,
    label: 'Switch',
    category: 'form',
    defaultWidth: 48,
    defaultHeight: 24,
    defaultProps: { fill: '#cccccc', stroke: 'none' },
  },
  {
    type: ElementType.SLIDER,
    label: 'Slider',
    category: 'form',
    defaultWidth: 200,
    defaultHeight: 24,
    defaultProps: { fill: '#e0e0e0', stroke: '#cccccc' },
  },
  {
    type: ElementType.RATING,
    label: 'Rating',
    category: 'form',
    defaultWidth: 150,
    defaultHeight: 24,
    defaultProps: { fill: 'none', stroke: 'none', text: '\u2605\u2605\u2605\u2605\u2605' },
  },
  {
    type: ElementType.FILE_UPLOAD,
    label: 'File Upload',
    category: 'form',
    defaultWidth: 200,
    defaultHeight: 80,
    defaultProps: { fill: '#f5f5f5', stroke: '#cccccc', text: 'Upload File', cornerRadius: 4 },
  },
  {
    type: ElementType.TABLE,
    label: 'Table',
    category: 'form',
    defaultWidth: 300,
    defaultHeight: 200,
    defaultProps: { fill: '#ffffff', stroke: '#cccccc' },
  },
  {
    type: ElementType.FORM_LABEL,
    label: 'Form Label',
    category: 'form',
    defaultWidth: 100,
    defaultHeight: 24,
    defaultProps: { fill: 'none', stroke: 'none', text: 'Label' },
  },
  {
    type: ElementType.STATUS_BAR,
    label: 'Status Bar',
    category: 'mobile',
    defaultWidth: 375,
    defaultHeight: 44,
    defaultProps: { fill: '#ffffff', stroke: 'none' },
  },
  {
    type: ElementType.NAV_BAR,
    label: 'Nav Bar',
    category: 'mobile',
    defaultWidth: 375,
    defaultHeight: 44,
    defaultProps: { fill: '#ffffff', stroke: '#e0e0e0' },
  },
  {
    type: ElementType.TOP_BAR,
    label: 'Top Bar',
    category: 'mobile',
    defaultWidth: 375,
    defaultHeight: 44,
    defaultProps: { fill: '#ffffff', stroke: '#e0e0e0' },
  },
  {
    type: ElementType.BOTTOM_BAR,
    label: 'Bottom Bar',
    category: 'mobile',
    defaultWidth: 375,
    defaultHeight: 50,
    defaultProps: { fill: '#ffffff', stroke: '#e0e0e0' },
  },
  {
    type: ElementType.CARD,
    label: 'Card',
    category: 'mobile',
    defaultWidth: 300,
    defaultHeight: 180,
    defaultProps: { fill: '#ffffff', stroke: '#e0e0e0', cornerRadius: 8 },
  },
  {
    type: ElementType.LIST_ITEM,
    label: 'List Item',
    category: 'mobile',
    defaultWidth: 375,
    defaultHeight: 64,
    defaultProps: { fill: '#ffffff', stroke: '#e0e0e0' },
  },
  {
    type: ElementType.DRAWER,
    label: 'Drawer',
    category: 'mobile',
    defaultWidth: 280,
    defaultHeight: 500,
    defaultProps: { fill: '#ffffff', stroke: '#e0e0e0' },
  },
  {
    type: ElementType.MODAL,
    label: 'Modal',
    category: 'mobile',
    defaultWidth: 320,
    defaultHeight: 240,
    defaultProps: { fill: '#ffffff', stroke: '#cccccc', cornerRadius: 8 },
  },
  {
    type: ElementType.AVATAR,
    label: 'Avatar',
    category: 'common',
    defaultWidth: 48,
    defaultHeight: 48,
    defaultProps: { fill: '#e0e0e0', stroke: 'none' },
  },
  {
    type: ElementType.TEXT,
    label: 'Text',
    category: 'common',
    defaultWidth: 200,
    defaultHeight: 30,
    defaultProps: { fill: 'none', stroke: 'none', text: 'Text' },
  },
  {
    type: ElementType.ICON,
    label: 'Icon',
    category: 'common',
    defaultWidth: 32,
    defaultHeight: 32,
    defaultProps: { fill: 'none', stroke: '#333333' },
  },
  {
    type: ElementType.IMAGE_PLACEHOLDER,
    label: 'Image',
    category: 'common',
    defaultWidth: 200,
    defaultHeight: 150,
    defaultProps: { fill: '#f0f0f0', stroke: '#cccccc', text: 'Image' },
  },
  {
    type: ElementType.CHART_PLACEHOLDER,
    label: 'Chart',
    category: 'common',
    defaultWidth: 300,
    defaultHeight: 200,
    defaultProps: { fill: '#f0f0f0', stroke: '#cccccc', text: 'Chart' },
  },
]
