import type { MaintenanceTemplate } from '@/types'

export const maintenanceTemplates: MaintenanceTemplate[] = [
  {
    gearType: 'running_shoe',
    name: '清洗跑鞋',
    cycleDays: 30,
    maxUsage: 500,
    maxUsageUnit: 'km',
    steps: [
      '取出鞋垫和鞋带',
      '用温水浸泡鞋面5分钟',
      '用中性洗涤剂和软毛刷擦洗鞋面',
      '用清水冲洗干净',
      '用毛巾吸去多余水分',
      '放在通风处阴干，避免阳光直射',
      '干透后放回鞋垫和鞋带',
    ],
    tools: ['软毛刷', '中性洗涤剂', '毛巾', '温水'],
  },
  {
    gearType: 'running_shoe',
    name: '退役跑鞋',
    cycleDays: 0,
    maxUsage: 800,
    maxUsageUnit: 'km',
    steps: [
      '检查鞋底磨损程度，看是否磨平',
      '按压中底检查缓震是否失效',
      '检查鞋面是否有破裂',
      '如果缓震失效或鞋底磨平，建议退役',
      '退役的跑鞋可做日常休闲鞋使用',
    ],
    tools: [],
  },
  {
    gearType: 'racket',
    name: '换线',
    cycleDays: 90,
    maxUsage: 50,
    maxUsageUnit: 'times',
    steps: [
      '用剪线钳剪断旧线，从中间开始剪',
      '取下旧线，清洁拍框上的残留物',
      '选择合适磅数的新线',
      '用穿线机穿新线，先穿竖线再穿横线',
      '拉紧到目标磅数',
      '检查线的张力是否均匀',
    ],
    tools: ['穿线机', '新拍线', '剪线钳'],
  },
  {
    gearType: 'racket',
    name: '更换吸汗带',
    cycleDays: 60,
    maxUsage: 30,
    maxUsageUnit: 'times',
    steps: [
      '撕掉旧的吸汗带',
      '用湿布清洁拍柄，去除残留胶水',
      '从拍柄底部开始缠绕新吸汗带',
      '保持适当重叠（约1/3宽度）',
      '缠绕至拍柄顶部',
      '用胶带固定末端',
    ],
    tools: ['新吸汗带', '固定胶带'],
  },
  {
    gearType: 'bicycle',
    name: '打气',
    cycleDays: 14,
    maxUsage: 0,
    maxUsageUnit: 'km',
    steps: [
      '用胎压计检查当前胎压',
      '参考轮胎侧面标注的推荐胎压',
      '用打气筒给前轮打气至推荐值',
      '给后轮打气至推荐值',
      '检查气门芯是否漏气',
      '一周后复查胎压',
    ],
    tools: ['打气筒', '胎压计'],
  },
  {
    gearType: 'bicycle',
    name: '链条上油',
    cycleDays: 60,
    maxUsage: 200,
    maxUsageUnit: 'km',
    steps: [
      '用抹布擦拭链条上的灰尘和旧油',
      '在旧报纸上操作避免弄脏地面',
      '在链条每个链接处滴一滴润滑油',
      '转动踏板几圈让油均匀分布',
      '等待5分钟让油渗透',
      '用抹布擦去链条表面多余的油',
    ],
    tools: ['链条润滑油', '抹布', '旧报纸'],
  },
  {
    gearType: 'bicycle',
    name: '退役自行车',
    cycleDays: 0,
    maxUsage: 3000,
    maxUsageUnit: 'km',
    steps: [
      '检查车架是否有裂纹或变形',
      '检查变速系统是否顺畅',
      '检查刹车系统是否有效',
      '检查轮组是否偏摆',
      '如有多项无法修复的问题，建议退役',
    ],
    tools: [],
  },
  {
    gearType: 'yoga_mat',
    name: '清洗瑜伽垫',
    cycleDays: 14,
    maxUsage: 30,
    maxUsageUnit: 'hours',
    steps: [
      '将瑜伽垫平铺展开',
      '均匀喷洒瑜伽垫清洁液',
      '用湿布从一端擦向另一端',
      '重点擦拭手脚接触的区域',
      '翻面重复以上步骤',
      '挂在通风处自然晾干',
      '完全干透后卷起存放',
    ],
    tools: ['瑜伽垫清洁喷雾', '湿布'],
  },
  {
    gearType: 'yoga_mat',
    name: '退役瑜伽垫',
    cycleDays: 0,
    maxUsage: 500,
    maxUsageUnit: 'hours',
    steps: [
      '检查表面防滑性，用手掌摩擦测试',
      '检查厚度是否明显变薄',
      '检查是否有撕裂或脱皮',
      '如果防滑性严重下降，建议退役',
      '旧瑜伽垫可裁剪做地垫使用',
    ],
    tools: [],
  },
]

export function getTemplatesForType(gearType: string): MaintenanceTemplate[] {
  return maintenanceTemplates.filter((t) => t.gearType === gearType)
}
