import type { Book, Family, BorrowRecord } from '../types';
import { generateId, today, addDays } from './storage';

export const mockBooks: Book[] = [
  {
    id: generateId(),
    title: '好饿的毛毛虫',
    ageRange: '3-4岁',
    themes: ['认知启蒙', '自然科学'],
    pages: 24,
    hasMechanism: true,
    damageLocation: '',
    coverUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=colorful%20caterpillar%20children%20book%20cover%20cute%20illustration&image_size=square',
    status: 'available',
    createdAt: addDays(today(), -30),
  },
  {
    id: generateId(),
    title: '猜猜我有多爱你',
    ageRange: '3-4岁',
    themes: ['亲情温暖', '童话故事'],
    pages: 32,
    hasMechanism: false,
    damageLocation: '封面有轻微折痕',
    coverUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=cute%20bunny%20rabbit%20family%20love%20children%20book%20cover%20warm%20illustration&image_size=square',
    status: 'borrowed',
    createdAt: addDays(today(), -28),
  },
  {
    id: generateId(),
    title: '我爸爸',
    ageRange: '3-4岁',
    themes: ['亲情温暖', '勇敢成长'],
    pages: 32,
    hasMechanism: false,
    damageLocation: '',
    coverUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=funny%20father%20daddy%20superhero%20children%20book%20cover%20cartoon&image_size=square',
    status: 'available',
    createdAt: addDays(today(), -25),
  },
  {
    id: generateId(),
    title: '大卫，不可以',
    ageRange: '3-4岁',
    themes: ['习惯养成', '情绪管理'],
    pages: 32,
    hasMechanism: false,
    damageLocation: '',
    coverUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=naughty%20boy%20david%20children%20book%20cover%20funny%20cartoon&image_size=square',
    status: 'borrowed',
    createdAt: addDays(today(), -22),
  },
  {
    id: generateId(),
    title: '蚯蚓的日记',
    ageRange: '5-6岁',
    themes: ['自然科学', '创意想象'],
    pages: 40,
    hasMechanism: false,
    damageLocation: '',
    coverUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=cute%20worm%20diary%20journal%20children%20book%20cover%20illustration&image_size=square',
    status: 'available',
    createdAt: addDays(today(), -20),
  },
  {
    id: generateId(),
    title: '神奇飞书',
    ageRange: '5-6岁',
    themes: ['创意想象', '艺术审美'],
    pages: 48,
    hasMechanism: true,
    damageLocation: '第15页边角破损',
    coverUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=magical%20flying%20books%20fantasy%20children%20book%20cover%20dreamy&image_size=square',
    status: 'damaged',
    createdAt: addDays(today(), -18),
  },
  {
    id: generateId(),
    title: '菲菲生气了',
    ageRange: '3-4岁',
    themes: ['情绪管理', '亲情温暖'],
    pages: 32,
    hasMechanism: false,
    damageLocation: '',
    coverUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=angry%20girl%20sophie%20emotion%20children%20book%20cover%20colorful&image_size=square',
    status: 'available',
    createdAt: addDays(today(), -15),
  },
  {
    id: generateId(),
    title: '地图（人文版）',
    ageRange: '7-8岁',
    themes: ['地理旅行', '历史文化'],
    pages: 112,
    hasMechanism: false,
    damageLocation: '',
    coverUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=world%20map%20atlas%20children%20book%20cover%20colorful%20illustration&image_size=square',
    status: 'available',
    createdAt: addDays(today(), -12),
  },
  {
    id: generateId(),
    title: '青蛙和蟾蜍',
    ageRange: '5-6岁',
    themes: ['社交友谊', '童话故事'],
    pages: 64,
    hasMechanism: false,
    damageLocation: '',
    coverUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=frog%20and%20toad%20friends%20children%20book%20cover%20cute%20vintage&image_size=square',
    status: 'borrowed',
    createdAt: addDays(today(), -10),
  },
  {
    id: generateId(),
    title: '小黑鱼',
    ageRange: '3-4岁',
    themes: ['勇敢成长', '自然科学', '社交友谊'],
    pages: 36,
    hasMechanism: false,
    damageLocation: '',
    coverUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=little%20black%20fish%20ocean%20sea%20children%20book%20cover%20watercolor&image_size=square',
    status: 'available',
    createdAt: addDays(today(), -8),
  },
  {
    id: generateId(),
    title: '数一数，亲了几下',
    ageRange: '0-2岁',
    themes: ['认知启蒙', '亲情温暖', '数学逻辑'],
    pages: 20,
    hasMechanism: true,
    damageLocation: '',
    coverUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=baby%20kiss%20counting%20numbers%20children%20book%20cover%20soft%20cute&image_size=square',
    status: 'available',
    createdAt: addDays(today(), -6),
  },
  {
    id: generateId(),
    title: '学会爱自己',
    ageRange: '5-6岁',
    themes: ['安全教育', '情绪管理', '习惯养成'],
    pages: 48,
    hasMechanism: false,
    damageLocation: '',
    coverUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=self%20love%20safety%20education%20children%20book%20cover%20warm%20heart&image_size=square',
    status: 'available',
    createdAt: addDays(today(), -4),
  },
];

export const mockFamilies: Family[] = [
  { id: generateId(), name: '小明家', childAge: 4, contact: '微信：xiaoming_mom' },
  { id: generateId(), name: '朵朵家', childAge: 3, contact: '微信：dododad' },
  { id: generateId(), name: '乐乐家', childAge: 6, contact: '微信：lele_family' },
  { id: generateId(), name: '糖糖家', childAge: 5, contact: '微信：tangtang2020' },
  { id: generateId(), name: '豆豆家', childAge: 2, contact: '微信：doudou_mama' },
];

export const mockBorrowRecords: BorrowRecord[] = [
  {
    id: generateId(),
    bookId: mockBooks[1].id,
    familyId: mockFamilies[0].id,
    childAge: 4,
    borrowDate: addDays(today(), -15),
    expectedReturnDate: addDays(today(), -1),
    willingToExchange: true,
    status: 'overdue',
  },
  {
    id: generateId(),
    bookId: mockBooks[3].id,
    familyId: mockFamilies[1].id,
    childAge: 3,
    borrowDate: addDays(today(), -8),
    expectedReturnDate: addDays(today(), 6),
    willingToExchange: false,
    status: 'borrowed',
  },
  {
    id: generateId(),
    bookId: mockBooks[8].id,
    familyId: mockFamilies[2].id,
    childAge: 6,
    borrowDate: addDays(today(), -5),
    expectedReturnDate: addDays(today(), 9),
    willingToExchange: true,
    status: 'borrowed',
  },
  {
    id: generateId(),
    bookId: mockBooks[0].id,
    familyId: mockFamilies[3].id,
    childAge: 5,
    borrowDate: addDays(today(), -25),
    expectedReturnDate: addDays(today(), -11),
    actualReturnDate: addDays(today(), -12),
    willingToExchange: false,
    damageCheck: { missingPages: false, doodles: false, tornPages: false, stickers: false, accessories: false },
    status: 'returned',
  },
  {
    id: generateId(),
    bookId: mockBooks[6].id,
    familyId: mockFamilies[0].id,
    childAge: 4,
    borrowDate: addDays(today(), -30),
    expectedReturnDate: addDays(today(), -16),
    actualReturnDate: addDays(today(), -17),
    willingToExchange: true,
    damageCheck: { missingPages: false, doodles: true, tornPages: false, stickers: false, accessories: false },
    damageNotes: '第8页有小孩涂鸦，不影响阅读',
    status: 'returned',
  },
];
