import type { Product, Order, Inspection, PickupRecord } from '@/types';

const now = new Date();
const hoursAgo = (h: number) => new Date(now.getTime() - h * 60 * 60 * 1000).toISOString();
const hoursLater = (h: number) => new Date(now.getTime() + h * 60 * 60 * 1000).toISOString();

export const mockProducts: Product[] = [
  {
    id: 'p1',
    name: '厄瓜多尔白虾',
    spec: '2kg/盒 (40-50只)',
    tempZone: 'frozen',
    arrivalTime: hoursAgo(2),
    supplier: '大洋海产',
    boxNumber: 'BOX-A001',
    photo: 'https://images.unsplash.com/photo-1565680018434-b513d5e5fd47?w=400&h=300&fit=crop',
    createdAt: hoursAgo(5),
  },
  {
    id: 'p2',
    name: '澳洲和牛牛排',
    spec: '200g/片 x 5片',
    tempZone: 'frozen',
    arrivalTime: hoursAgo(2),
    supplier: '牛冠食品',
    boxNumber: 'BOX-A002',
    photo: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=400&h=300&fit=crop',
    createdAt: hoursAgo(5),
  },
  {
    id: 'p3',
    name: '梦龙冰淇淋',
    spec: '64g/支 x 6支',
    tempZone: 'frozen',
    arrivalTime: hoursAgo(1),
    supplier: '和路雪',
    boxNumber: 'BOX-B001',
    photo: 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=400&h=300&fit=crop',
    createdAt: hoursAgo(4),
  },
  {
    id: 'p4',
    name: '有机鲜牛奶',
    spec: '1L/瓶 x 2瓶',
    tempZone: 'refrigerated',
    arrivalTime: hoursAgo(3),
    supplier: '特仑苏',
    boxNumber: 'BOX-C001',
    photo: 'https://images.unsplash.com/photo-1563636619-e9143da7973b?w=400&h=300&fit=crop',
    createdAt: hoursAgo(6),
  },
];

export const mockOrders: Order[] = [
  {
    id: 'o1',
    productId: 'p1',
    customerName: '张阿姨',
    phoneLast4: '1234',
    quantity: 2,
    pickupSlot: 'morning',
    hasIceBag: true,
    status: 'pending',
    createdAt: hoursAgo(4),
  },
  {
    id: 'o2',
    productId: 'p1',
    customerName: '李叔',
    phoneLast4: '5678',
    quantity: 1,
    pickupSlot: 'afternoon',
    hasIceBag: false,
    status: 'pending',
    createdAt: hoursAgo(4),
  },
  {
    id: 'o3',
    productId: 'p2',
    customerName: '王姐',
    phoneLast4: '9012',
    quantity: 1,
    pickupSlot: 'noon',
    hasIceBag: true,
    status: 'timeout',
    createdAt: hoursAgo(8),
  },
  {
    id: 'o4',
    productId: 'p2',
    customerName: '赵哥',
    phoneLast4: '3456',
    quantity: 3,
    pickupSlot: 'evening',
    hasIceBag: false,
    status: 'pending',
    createdAt: hoursAgo(3),
  },
  {
    id: 'o5',
    productId: 'p3',
    customerName: '陈小妹',
    phoneLast4: '7890',
    quantity: 2,
    pickupSlot: 'afternoon',
    hasIceBag: true,
    status: 'picked',
    createdAt: hoursAgo(3),
  },
  {
    id: 'o6',
    productId: 'p3',
    customerName: '刘大妈',
    phoneLast4: '2345',
    quantity: 1,
    pickupSlot: 'morning',
    hasIceBag: false,
    status: 'pending',
    createdAt: hoursAgo(3),
  },
  {
    id: 'o7',
    productId: 'p4',
    customerName: '孙老师',
    phoneLast4: '6789',
    quantity: 1,
    pickupSlot: 'morning',
    hasIceBag: true,
    status: 'picked',
    createdAt: hoursAgo(5),
  },
  {
    id: 'o8',
    productId: 'p4',
    customerName: '周医生',
    phoneLast4: '0123',
    quantity: 2,
    pickupSlot: 'evening',
    hasIceBag: true,
    status: 'pending',
    createdAt: hoursAgo(5),
  },
];

export const mockInspections: Inspection[] = [
  {
    id: 'i1',
    productId: 'p1',
    temperature: -20,
    hasDamage: false,
    hasMelt: false,
    shortageQuantity: 0,
    photos: [],
    inspectedAt: hoursAgo(2),
  },
  {
    id: 'i2',
    productId: 'p2',
    temperature: -15,
    hasDamage: true,
    damageNote: '外包装轻微压损，内部完好',
    hasMelt: false,
    shortageQuantity: 0,
    photos: [],
    inspectedAt: hoursAgo(2),
  },
  {
    id: 'i3',
    productId: 'p3',
    temperature: -8,
    hasDamage: false,
    hasMelt: true,
    meltNote: '运输途中温度偏高，有轻微软化',
    shortageQuantity: 1,
    shortageNote: '缺少1盒，已联系供应商补发',
    photos: [],
    inspectedAt: hoursAgo(1),
  },
];

export const mockPickupRecords: PickupRecord[] = [
  {
    id: 'pr1',
    orderId: 'o5',
    pickedAt: hoursAgo(1),
    hasException: false,
    photos: [],
  },
  {
    id: 'pr2',
    orderId: 'o7',
    pickedAt: hoursAgo(3),
    hasException: false,
    photos: [],
  },
];
