import type { Point, InspectionRecord, AnomalyTicket } from '../types';

const img = (prompt: string) =>
  `https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=${encodeURIComponent(prompt)}&image_size=square`;

const today = new Date();
const formatDate = (d: Date) => d.toISOString().split('T')[0];
const formatDateTime = (d: Date) => d.toISOString();

const daysAgo = (days: number) => {
  const d = new Date(today);
  d.setDate(d.getDate() - days);
  return d;
};

const daysLater = (days: number) => {
  const d = new Date(today);
  d.setDate(d.getDate() + days);
  return d;
};

export const initialPoints: Point[] = [
  {
    id: 'p1',
    area: '1楼',
    deviceType: '灭火器',
    deviceNo: 'FMQ-001',
    personInCharge: '张三',
    inspectionCycle: 30,
    photo: img('red fire extinguisher in modern office hallway'),
    lastInspectionDate: formatDate(daysAgo(25)),
    nextInspectionDate: formatDate(daysLater(5)),
    createdAt: formatDateTime(daysAgo(90)),
    updatedAt: formatDateTime(daysAgo(25)),
  },
  {
    id: 'p2',
    area: '1楼',
    deviceType: '应急灯',
    deviceNo: 'YJD-001',
    personInCharge: '李四',
    inspectionCycle: 15,
    photo: img('emergency exit light in office building corridor'),
    lastInspectionDate: formatDate(daysAgo(20)),
    nextInspectionDate: formatDate(daysAgo(5)),
    createdAt: formatDateTime(daysAgo(90)),
    updatedAt: formatDateTime(daysAgo(20)),
  },
  {
    id: 'p3',
    area: '1楼',
    deviceType: '安全出口贴纸',
    deviceNo: 'TIE-001',
    personInCharge: '王五',
    inspectionCycle: 30,
    photo: img('green emergency exit sign sticker on wall'),
    lastInspectionDate: formatDate(daysAgo(28)),
    nextInspectionDate: formatDate(daysLater(2)),
    createdAt: formatDateTime(daysAgo(90)),
    updatedAt: formatDateTime(daysAgo(28)),
  },
  {
    id: 'p4',
    area: '2楼',
    deviceType: '灭火器',
    deviceNo: 'FMQ-002',
    personInCharge: '赵六',
    inspectionCycle: 30,
    photo: img('fire extinguisher cabinet near office staircase'),
    lastInspectionDate: formatDate(daysAgo(35)),
    nextInspectionDate: formatDate(daysAgo(5)),
    createdAt: formatDateTime(daysAgo(90)),
    updatedAt: formatDateTime(daysAgo(35)),
  },
  {
    id: 'p5',
    area: '2楼',
    deviceType: '应急灯',
    deviceNo: 'YJD-002',
    personInCharge: '钱七',
    inspectionCycle: 15,
    photo: img('ceiling mounted emergency light in office'),
    lastInspectionDate: formatDate(daysAgo(10)),
    nextInspectionDate: formatDate(daysLater(5)),
    createdAt: formatDateTime(daysAgo(90)),
    updatedAt: formatDateTime(daysAgo(10)),
  },
  {
    id: 'p6',
    area: '2楼',
    deviceType: '安全出口贴纸',
    deviceNo: 'TIE-002',
    personInCharge: '孙八',
    inspectionCycle: 30,
    photo: img('illuminated exit sign above office door'),
    lastInspectionDate: formatDate(daysAgo(32)),
    nextInspectionDate: formatDate(daysAgo(2)),
    createdAt: formatDateTime(daysAgo(90)),
    updatedAt: formatDateTime(daysAgo(32)),
  },
  {
    id: 'p7',
    area: '3楼',
    deviceType: '灭火器',
    deviceNo: 'FMQ-003',
    personInCharge: '周九',
    inspectionCycle: 30,
    photo: img('fire extinguisher with inspection tag'),
    lastInspectionDate: formatDate(daysAgo(5)),
    nextInspectionDate: formatDate(daysLater(25)),
    createdAt: formatDateTime(daysAgo(90)),
    updatedAt: formatDateTime(daysAgo(5)),
  },
  {
    id: 'p8',
    area: '3楼',
    deviceType: '应急灯',
    deviceNo: 'YJD-003',
    personInCharge: '吴十',
    inspectionCycle: 15,
    photo: img('emergency lighting system in building corridor'),
    lastInspectionDate: formatDate(daysAgo(18)),
    nextInspectionDate: formatDate(daysAgo(3)),
    createdAt: formatDateTime(daysAgo(90)),
    updatedAt: formatDateTime(daysAgo(18)),
  },
  {
    id: 'p9',
    area: '3楼',
    deviceType: '安全出口贴纸',
    deviceNo: 'TIE-003',
    personInCharge: '郑一',
    inspectionCycle: 30,
    photo: img('green running man exit sign sticker'),
    lastInspectionDate: formatDate(daysAgo(3)),
    nextInspectionDate: formatDate(daysLater(27)),
    createdAt: formatDateTime(daysAgo(90)),
    updatedAt: formatDateTime(daysAgo(3)),
  },
  {
    id: 'p10',
    area: '1楼',
    deviceType: '灭火器',
    deviceNo: 'FMQ-004',
    personInCharge: '张三',
    inspectionCycle: 30,
    photo: img('fire extinguisher near reception desk'),
    lastInspectionDate: formatDate(daysAgo(3)),
    nextInspectionDate: formatDate(daysLater(27)),
    createdAt: formatDateTime(daysAgo(90)),
    updatedAt: formatDateTime(daysAgo(3)),
  },
  {
    id: 'p11',
    area: '2楼',
    deviceType: '灭火器',
    deviceNo: 'FMQ-005',
    personInCharge: '赵六',
    inspectionCycle: 30,
    photo: img('multiple fire extinguishers in rack'),
    lastInspectionDate: formatDate(daysAgo(8)),
    nextInspectionDate: formatDate(daysLater(22)),
    createdAt: formatDateTime(daysAgo(90)),
    updatedAt: formatDateTime(daysAgo(8)),
  },
  {
    id: 'p12',
    area: '3楼',
    deviceType: '应急灯',
    deviceNo: 'YJD-004',
    personInCharge: '吴十',
    inspectionCycle: 15,
    photo: img('battery backup emergency light'),
    lastInspectionDate: formatDate(daysAgo(12)),
    nextInspectionDate: formatDate(daysLater(3)),
    createdAt: formatDateTime(daysAgo(90)),
    updatedAt: formatDateTime(daysAgo(12)),
  },
];

export const initialInspectionRecords: InspectionRecord[] = [
  {
    id: 'r1',
    pointId: 'p1',
    status: 'normal',
    pressure: 1.2,
    inspector: '张三',
    inspectionTime: formatDateTime(daysAgo(25)),
    createdAt: formatDateTime(daysAgo(25)),
  },
  {
    id: 'r2',
    pointId: 'p2',
    status: 'anomaly',
    lightingStatus: '不亮',
    anomalyDescription: '应急灯电池老化，断电后无法持续照明',
    photo: img('broken emergency light with dark bulb'),
    inspector: '李四',
    inspectionTime: formatDateTime(daysAgo(20)),
    createdAt: formatDateTime(daysAgo(20)),
  },
  {
    id: 'r3',
    pointId: 'p3',
    status: 'normal',
    inspector: '王五',
    inspectionTime: formatDateTime(daysAgo(28)),
    createdAt: formatDateTime(daysAgo(28)),
  },
  {
    id: 'r4',
    pointId: 'p4',
    status: 'anomaly',
    pressure: 0.8,
    anomalyDescription: '灭火器压力不足，需要更换或充装',
    photo: img('fire extinguisher pressure gauge in red zone'),
    inspector: '赵六',
    inspectionTime: formatDateTime(daysAgo(35)),
    createdAt: formatDateTime(daysAgo(35)),
  },
  {
    id: 'r5',
    pointId: 'p5',
    status: 'normal',
    lightingStatus: '正常',
    inspector: '钱七',
    inspectionTime: formatDateTime(daysAgo(10)),
    createdAt: formatDateTime(daysAgo(10)),
  },
  {
    id: 'r6',
    pointId: 'p6',
    status: 'anomaly',
    anomalyDescription: '安全出口贴纸有污渍遮挡，需要更换',
    photo: img('dirty exit sign sticker partially covered'),
    inspector: '孙八',
    inspectionTime: formatDateTime(daysAgo(32)),
    createdAt: formatDateTime(daysAgo(32)),
  },
  {
    id: 'r7',
    pointId: 'p7',
    status: 'normal',
    pressure: 1.4,
    inspector: '周九',
    inspectionTime: formatDateTime(daysAgo(5)),
    createdAt: formatDateTime(daysAgo(5)),
  },
  {
    id: 'r8',
    pointId: 'p8',
    status: 'anomaly',
    lightingStatus: '闪烁',
    anomalyDescription: '应急灯灯泡接触不良，频繁闪烁',
    photo: img('flickering emergency light in dark corridor'),
    inspector: '吴十',
    inspectionTime: formatDateTime(daysAgo(18)),
    createdAt: formatDateTime(daysAgo(18)),
  },
  {
    id: 'r9',
    pointId: 'p9',
    status: 'normal',
    inspector: '郑一',
    inspectionTime: formatDateTime(daysAgo(3)),
    createdAt: formatDateTime(daysAgo(3)),
  },
  {
    id: 'r10',
    pointId: 'p10',
    status: 'normal',
    pressure: 1.3,
    inspector: '张三',
    inspectionTime: formatDateTime(daysAgo(3)),
    createdAt: formatDateTime(daysAgo(3)),
  },
  {
    id: 'r11',
    pointId: 'p11',
    status: 'anomaly',
    pressure: 0.9,
    anomalyDescription: '灭火器胶管老化有裂纹',
    photo: img('fire extinguisher with cracked hose'),
    inspector: '赵六',
    inspectionTime: formatDateTime(daysAgo(8)),
    createdAt: formatDateTime(daysAgo(8)),
  },
  {
    id: 'r12',
    pointId: 'p12',
    status: 'normal',
    lightingStatus: '正常',
    inspector: '吴十',
    inspectionTime: formatDateTime(daysAgo(12)),
    createdAt: formatDateTime(daysAgo(12)),
  },
];

export const initialAnomalyTickets: AnomalyTicket[] = [
  {
    id: 't1',
    inspectionRecordId: 'r2',
    pointId: 'p2',
    status: 'reported',
    description: '应急灯电池老化，断电后无法持续照明',
    reporter: '李四',
    repairer: '维修部-王工',
    reportTime: formatDateTime(daysAgo(20)),
    repairTime: formatDateTime(daysAgo(15)),
    createdAt: formatDateTime(daysAgo(20)),
    updatedAt: formatDateTime(daysAgo(15)),
  },
  {
    id: 't2',
    inspectionRecordId: 'r4',
    pointId: 'p4',
    status: 'pending',
    description: '灭火器压力不足，需要更换或充装',
    reporter: '赵六',
    reportTime: formatDateTime(daysAgo(35)),
    createdAt: formatDateTime(daysAgo(35)),
    updatedAt: formatDateTime(daysAgo(35)),
  },
  {
    id: 't3',
    inspectionRecordId: 'r6',
    pointId: 'p6',
    status: 'reviewed',
    description: '安全出口贴纸有污渍遮挡，需要更换',
    reporter: '孙八',
    repairer: '行政部-李姐',
    reviewer: '孙八',
    reportTime: formatDateTime(daysAgo(32)),
    repairTime: formatDateTime(daysAgo(28)),
    reviewTime: formatDateTime(daysAgo(25)),
    createdAt: formatDateTime(daysAgo(32)),
    updatedAt: formatDateTime(daysAgo(25)),
  },
  {
    id: 't4',
    inspectionRecordId: 'r8',
    pointId: 'p8',
    status: 'pending',
    description: '应急灯灯泡接触不良，频繁闪烁',
    reporter: '吴十',
    reportTime: formatDateTime(daysAgo(18)),
    createdAt: formatDateTime(daysAgo(18)),
    updatedAt: formatDateTime(daysAgo(18)),
  },
  {
    id: 't5',
    inspectionRecordId: 'r11',
    pointId: 'p11',
    status: 'reported',
    description: '灭火器胶管老化有裂纹',
    reporter: '赵六',
    repairer: '维修部-张工',
    reportTime: formatDateTime(daysAgo(8)),
    repairTime: formatDateTime(daysAgo(5)),
    createdAt: formatDateTime(daysAgo(8)),
    updatedAt: formatDateTime(daysAgo(5)),
  },
];
