import { Activity, Registration } from '@/types';

const now = new Date();
const toISO = (days: number, hours: number, minutes: number = 0): string => {
  const d = new Date(now);
  d.setDate(d.getDate() + days);
  d.setHours(hours, minutes, 0, 0);
  return d.toISOString();
};

export const mockActivities: Activity[] = [
  {
    id: 'act_001',
    title: '小区沙池挖沙派对',
    ageRange: '3-5岁',
    location: '阳光小区中心花园沙池',
    locationType: 'outdoor',
    startTime: toISO(0, 16, 0),
    endTime: toISO(0, 18, 0),
    description: '下午带娃来沙池挖沙！带上小铲子小桶，一起堆沙堡~',
    maxParticipants: 8,
    needParent: true,
    notes: '请带好防晒用品，自备挖沙工具，注意不要扬沙',
    coverEmoji: '🏖️',
    createdAt: toISO(-1, 10, 0),
    creatorName: '乐乐妈',
  },
  {
    id: 'act_002',
    title: '绘本共读时光',
    ageRange: '3-5岁',
    location: '邻里中心图书室',
    locationType: 'indoor',
    startTime: toISO(0, 19, 0),
    endTime: toISO(0, 20, 30),
    description: '每周三晚一起读绘本，讲故事，培养阅读好习惯。',
    maxParticipants: 10,
    needParent: true,
    notes: '本周读《好饿的毛毛虫》和《猜猜我有多爱你》',
    coverEmoji: '📚',
    createdAt: toISO(-2, 15, 0),
    creatorName: '轩轩爸',
  },
  {
    id: 'act_003',
    title: '儿童足球小联赛',
    ageRange: '6-8岁',
    location: '社区运动场',
    locationType: 'outdoor',
    startTime: toISO(1, 9, 30),
    endTime: toISO(1, 11, 30),
    description: '周末上午来踢球！练身体交朋友，简单分组对抗~',
    maxParticipants: 14,
    needParent: false,
    notes: '穿运动鞋运动服，带水杯。家长可在旁观看',
    coverEmoji: '⚽',
    createdAt: toISO(-3, 20, 0),
    creatorName: '大壮爸',
  },
  {
    id: 'act_004',
    title: '乐高积木创意拼搭',
    ageRange: '6-8岁',
    location: '3号楼2单元活动室',
    locationType: 'indoor',
    startTime: toISO(2, 14, 0),
    endTime: toISO(2, 16, 30),
    description: '小朋友自带乐高来分享，一起拼搭创意作品！',
    maxParticipants: 6,
    needParent: true,
    notes: '可自愿带1-2套乐高积木，活动结束后各自带回',
    coverEmoji: '🧩',
    createdAt: toISO(-1, 9, 0),
    creatorName: '小美妈',
  },
  {
    id: 'act_005',
    title: '周末户外野餐会',
    ageRange: '全年龄段',
    location: '滨河公园大草坪',
    locationType: 'outdoor',
    startTime: toISO(5, 10, 0),
    endTime: toISO(5, 15, 0),
    description: '周六公园大野餐！每家带1-2个小菜或水果分享~',
    maxParticipants: 20,
    needParent: true,
    notes: '建议带野餐垫、湿巾，小朋友可以带风筝、泡泡机',
    coverEmoji: '🧺',
    createdAt: toISO(-5, 12, 0),
    creatorName: '果果妈',
  },
  {
    id: 'act_006',
    title: '幼儿游泳启蒙',
    ageRange: '3-5岁',
    location: '星光游泳馆亲子池',
    locationType: 'indoor',
    startTime: toISO(3, 17, 0),
    endTime: toISO(3, 18, 0),
    description: '婴幼儿亲子游泳体验，需要1名家长下水陪同。',
    maxParticipants: 5,
    needParent: true,
    notes: '带泳衣、泳帽、浴巾，游泳馆提供救生圈',
    coverEmoji: '🏊',
    createdAt: toISO(-2, 14, 0),
    creatorName: '安安妈',
  },
  {
    id: 'act_007',
    title: '儿童美术手工课',
    ageRange: '6-8岁',
    location: '2号楼B1艺术教室',
    locationType: 'indoor',
    startTime: toISO(6, 14, 30),
    endTime: toISO(6, 16, 30),
    description: '本周主题：黏土动物世界。材料全包，作品可带走。',
    maxParticipants: 10,
    needParent: false,
    notes: '建议穿旧衣服，黏土可能粘到衣服上',
    coverEmoji: '🎨',
    createdAt: toISO(-1, 18, 0),
    creatorName: '豆豆妈',
  },
  {
    id: 'act_008',
    title: '小区自行车骑行队',
    ageRange: '9-12岁',
    location: '小区外环绿道',
    locationType: 'outdoor',
    startTime: toISO(1, 16, 0),
    endTime: toISO(1, 17, 30),
    description: '高年级小朋友一起骑车绕小区绿道，练习车技~',
    maxParticipants: 8,
    needParent: false,
    notes: '必须佩戴头盔，建议带护肘护膝',
    coverEmoji: '🚴',
    createdAt: toISO(-4, 10, 0),
    creatorName: '飞飞爸',
  },
  {
    id: 'act_009',
    title: '小区亲子涂鸦日',
    ageRange: '3-8岁',
    location: '中心广场凉亭',
    locationType: 'outdoor',
    startTime: toISO(4, 15, 0),
    endTime: toISO(4, 17, 30),
    description: '户外地面涂鸦！小朋友一起用粉笔画彩虹、小动物，尽情发挥想象力~',
    maxParticipants: 10,
    needParent: true,
    notes: '提供粉笔和彩笔，建议穿不怕脏的衣服，画完统一清理',
    coverEmoji: '🖍️',
    createdAt: toISO(-2, 9, 30),
    creatorName: '我',
  },
];

export const mockRegistrations: Registration[] = [
  {
    id: 'reg_001',
    activityId: 'act_001',
    childNickname: '乐乐',
    allergyInfo: '花生',
    attendeeCount: 1,
    parentPhone: '138****1234',
    status: 'confirmed',
    waitlistNumber: null,
    registeredAt: toISO(-1, 11, 0),
  },
  {
    id: 'reg_002',
    activityId: 'act_001',
    childNickname: '糖糖',
    allergyInfo: '无',
    attendeeCount: 1,
    parentPhone: '139****5678',
    status: 'confirmed',
    waitlistNumber: null,
    registeredAt: toISO(-1, 12, 0),
  },
  {
    id: 'reg_003',
    activityId: 'act_001',
    childNickname: '小雨',
    allergyInfo: '芒果',
    attendeeCount: 1,
    parentPhone: '137****9012',
    status: 'confirmed',
    waitlistNumber: null,
    registeredAt: toISO(-1, 13, 0),
  },
  {
    id: 'reg_004',
    activityId: 'act_002',
    childNickname: '轩轩',
    allergyInfo: '无',
    attendeeCount: 1,
    parentPhone: '136****3456',
    status: 'confirmed',
    waitlistNumber: null,
    registeredAt: toISO(-2, 16, 0),
  },
  {
    id: 'reg_005',
    activityId: 'act_002',
    childNickname: '萌萌',
    allergyInfo: '海鲜',
    attendeeCount: 1,
    parentPhone: '135****7890',
    status: 'confirmed',
    waitlistNumber: null,
    registeredAt: toISO(-2, 17, 0),
  },
  {
    id: 'reg_006',
    activityId: 'act_003',
    childNickname: '大壮',
    allergyInfo: '无',
    attendeeCount: 1,
    parentPhone: '134****2345',
    status: 'confirmed',
    waitlistNumber: null,
    registeredAt: toISO(-3, 21, 0),
  },
  {
    id: 'reg_007',
    activityId: 'act_003',
    childNickname: '小虎',
    allergyInfo: '无',
    attendeeCount: 1,
    parentPhone: '133****6789',
    status: 'confirmed',
    waitlistNumber: null,
    registeredAt: toISO(-3, 22, 0),
  },
  {
    id: 'reg_008',
    activityId: 'act_003',
    childNickname: '浩浩',
    allergyInfo: '鸡蛋',
    attendeeCount: 1,
    parentPhone: '132****0123',
    status: 'confirmed',
    waitlistNumber: null,
    registeredAt: toISO(-2, 8, 0),
  },
  {
    id: 'reg_009',
    activityId: 'act_003',
    childNickname: '阳阳',
    allergyInfo: '无',
    attendeeCount: 1,
    parentPhone: '131****4567',
    status: 'confirmed',
    waitlistNumber: null,
    registeredAt: toISO(-2, 9, 0),
  },
  {
    id: 'reg_010',
    activityId: 'act_003',
    childNickname: '亮亮',
    allergyInfo: '无',
    attendeeCount: 1,
    parentPhone: '130****8901',
    status: 'waitlist',
    waitlistNumber: 1,
    registeredAt: toISO(-2, 10, 0),
  },
  {
    id: 'reg_011',
    activityId: 'act_004',
    childNickname: '小美',
    allergyInfo: '无',
    attendeeCount: 1,
    parentPhone: '188****2233',
    status: 'confirmed',
    waitlistNumber: null,
    registeredAt: toISO(-1, 10, 0),
  },
  {
    id: 'reg_012',
    activityId: 'act_004',
    childNickname: '一一',
    allergyInfo: '牛奶',
    attendeeCount: 1,
    parentPhone: '187****4455',
    status: 'confirmed',
    waitlistNumber: null,
    registeredAt: toISO(-1, 11, 0),
  },
  {
    id: 'reg_013',
    activityId: 'act_004',
    childNickname: '朵朵',
    allergyInfo: '无',
    attendeeCount: 1,
    parentPhone: '186****6677',
    status: 'waitlist',
    waitlistNumber: 1,
    registeredAt: toISO(-1, 12, 0),
  },
  {
    id: 'reg_014',
    activityId: 'act_005',
    childNickname: '果果',
    allergyInfo: '坚果',
    attendeeCount: 2,
    parentPhone: '185****8899',
    status: 'confirmed',
    waitlistNumber: null,
    registeredAt: toISO(-5, 13, 0),
  },
  {
    id: 'reg_015',
    activityId: 'act_005',
    childNickname: '豆豆',
    allergyInfo: '无',
    attendeeCount: 1,
    parentPhone: '184****0011',
    status: 'confirmed',
    waitlistNumber: null,
    registeredAt: toISO(-4, 10, 0),
  },
  {
    id: 'reg_016',
    activityId: 'act_007',
    childNickname: '豆豆',
    allergyInfo: '无',
    attendeeCount: 1,
    parentPhone: '184****0011',
    status: 'confirmed',
    waitlistNumber: null,
    registeredAt: toISO(-1, 19, 0),
  },
  {
    id: 'reg_017',
    activityId: 'act_008',
    childNickname: '飞飞',
    allergyInfo: '无',
    attendeeCount: 1,
    parentPhone: '183****2233',
    status: 'confirmed',
    waitlistNumber: null,
    registeredAt: toISO(-4, 11, 0),
  },
  {
    id: 'reg_018',
    activityId: 'act_009',
    childNickname: '小柚子',
    allergyInfo: '无',
    attendeeCount: 2,
    parentPhone: '138****1111',
    status: 'confirmed',
    waitlistNumber: null,
    registeredAt: toISO(-2, 10, 0),
  },
  {
    id: 'reg_019',
    activityId: 'act_009',
    childNickname: '阿喵',
    allergyInfo: '芒果',
    attendeeCount: 1,
    parentPhone: '139****2222',
    status: 'confirmed',
    waitlistNumber: null,
    registeredAt: toISO(-2, 11, 0),
  },
  {
    id: 'reg_020',
    activityId: 'act_009',
    childNickname: '小汤圆',
    allergyInfo: '花生、海鲜',
    attendeeCount: 2,
    parentPhone: '137****3333',
    status: 'confirmed',
    waitlistNumber: null,
    registeredAt: toISO(-2, 13, 0),
  },
  {
    id: 'reg_021',
    activityId: 'act_009',
    childNickname: '叮当',
    allergyInfo: '牛奶',
    attendeeCount: 1,
    parentPhone: '136****4444',
    status: 'confirmed',
    waitlistNumber: null,
    registeredAt: toISO(-1, 9, 0),
  },
  {
    id: 'reg_022',
    activityId: 'act_009',
    childNickname: '毛豆',
    allergyInfo: '无',
    attendeeCount: 2,
    parentPhone: '135****5555',
    status: 'waitlist',
    waitlistNumber: 1,
    registeredAt: toISO(-1, 10, 0),
  },
  {
    id: 'reg_023',
    activityId: 'act_009',
    childNickname: '西米',
    allergyInfo: '鸡蛋',
    attendeeCount: 1,
    parentPhone: '134****6666',
    status: 'waitlist',
    waitlistNumber: 2,
    registeredAt: toISO(-1, 11, 30),
  },
  {
    id: 'reg_024',
    activityId: 'act_009',
    childNickname: '乐乐',
    allergyInfo: '无',
    attendeeCount: 1,
    parentPhone: '133****7777',
    status: 'cancelled',
    waitlistNumber: null,
    registeredAt: toISO(-3, 14, 0),
  },
  {
    id: 'reg_025',
    activityId: 'act_009',
    childNickname: '糖糖',
    allergyInfo: '草莓',
    attendeeCount: 2,
    parentPhone: '132****8888',
    status: 'cancelled',
    waitlistNumber: null,
    registeredAt: toISO(-3, 16, 0),
  },
];
