import { FoodItem, ClaimRecord, DisposalRecord } from '../types';
import { generateId } from './time';

const now = new Date();

function hoursAgo(hours: number): string {
  return new Date(now.getTime() - hours * 60 * 60 * 1000).toISOString();
}

function hoursLater(hours: number): string {
  return new Date(now.getTime() + hours * 60 * 60 * 1000).toISOString();
}

export const mockFoodItems: FoodItem[] = [
  {
    id: generateId(),
    name: '新鲜草莓',
    category: 'fruit',
    quantity: 20,
    remaining: 15,
    isOpened: true,
    allergens: [],
    meetingRoom: 'A101-创新厅',
    department: '产品部',
    endTime: hoursAgo(1),
    edibleHours: 4,
    photoUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=fresh%20strawberries%20in%20a%20white%20bowl%20on%20wooden%20table%20bright%20natural%20light&image_size=square_hd',
    description: '精选红颜草莓，果肉饱满多汁，酸甜可口',
    status: 'available',
    createdAt: hoursAgo(1),
  },
  {
    id: generateId(),
    name: '奶油蛋糕卷',
    category: 'snack',
    quantity: 12,
    remaining: 8,
    isOpened: true,
    allergens: ['dairy', 'gluten'],
    meetingRoom: 'A201-董事会议室',
    department: '行政部',
    endTime: hoursAgo(0.5),
    edibleHours: 6,
    photoUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=cream%20swiss%20roll%20cake%20sliced%20on%20white%20plate%20elegant%20tea%20setting&image_size=square_hd',
    description: '进口奶油制作，口感绵密，甜度适中',
    status: 'available',
    createdAt: hoursAgo(0.5),
  },
  {
    id: generateId(),
    name: '混合坚果拼盘',
    category: 'snack',
    quantity: 30,
    remaining: 25,
    isOpened: true,
    allergens: ['nuts'],
    meetingRoom: 'B101-培训室',
    department: '人力资源部',
    endTime: hoursAgo(2),
    edibleHours: 8,
    photoUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=mixed%20nuts%20platter%20almonds%20walnuts%20cashews%20in%20wooden%20bowl%20warm%20lighting&image_size=square_hd',
    description: '包含杏仁、核桃、腰果、夏威夷果等多种坚果',
    status: 'available',
    createdAt: hoursAgo(2),
  },
  {
    id: generateId(),
    name: '鲜榨橙汁',
    category: 'beverage',
    quantity: 10,
    remaining: 6,
    isOpened: true,
    allergens: [],
    meetingRoom: 'B201-头脑风暴室',
    department: '运营部',
    endTime: hoursAgo(1.5),
    edibleHours: 3,
    photoUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=fresh%20orange%20juice%20in%20clear%20glass%20with%20orange%20slices%20bright%20refreshing&image_size=square_hd',
    description: '100%鲜榨橙汁，无添加糖分，维C满满',
    status: 'available',
    createdAt: hoursAgo(1.5),
  },
  {
    id: generateId(),
    name: '蓝莓马芬蛋糕',
    category: 'snack',
    quantity: 24,
    remaining: 24,
    isOpened: false,
    allergens: ['dairy', 'gluten'],
    meetingRoom: 'C101-多功能厅',
    department: '市场部',
    endTime: hoursAgo(0.2),
    edibleHours: 12,
    photoUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=blueberry%20muffins%20with%20fresh%20blueberries%20on%20top%20golden%20brown&image_size=square_hd',
    description: '精选蓝莓，蛋糕松软，早餐下午茶皆宜',
    status: 'available',
    createdAt: hoursAgo(0.2),
  },
  {
    id: generateId(),
    name: '车厘子',
    category: 'fruit',
    quantity: 5,
    remaining: 2,
    isOpened: true,
    allergens: [],
    meetingRoom: 'C201-视频会议室',
    department: '技术部',
    endTime: hoursAgo(3),
    edibleHours: 5,
    photoUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=fresh%20cherries%20in%20glass%20bowl%20dark%20red%20juicy%20premium%20quality&image_size=square_hd',
    description: 'JJJ级进口车厘子，果肉脆甜',
    status: 'partially_claimed',
    createdAt: hoursAgo(3),
  },
  {
    id: generateId(),
    name: '拿铁咖啡',
    category: 'beverage',
    quantity: 8,
    remaining: 8,
    isOpened: false,
    allergens: ['dairy'],
    meetingRoom: 'D101-小会议室',
    department: '财务部',
    endTime: hoursAgo(0.5),
    edibleHours: 2,
    photoUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=latte%20coffee%20with%20latte%20art%20heart%20shape%20in%20white%20ceramic%20cup&image_size=square_hd',
    description: '现磨意式浓缩配鲜奶，丝滑醇厚',
    status: 'available',
    createdAt: hoursAgo(0.5),
  },
  {
    id: generateId(),
    name: '芒果班戟',
    category: 'snack',
    quantity: 16,
    remaining: 0,
    isOpened: true,
    allergens: ['dairy', 'gluten'],
    meetingRoom: 'A102-协作室',
    department: '设计部',
    endTime: hoursAgo(2),
    edibleHours: 6,
    photoUrl: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=mango%20pancake%20mango%20pudding%20cream%20dessert%20asian%20style%20elegant%20presentation&image_size=square_hd',
    description: '新鲜芒果果肉配奶油，皮薄馅足',
    status: 'fully_claimed',
    createdAt: hoursAgo(2),
  },
];

export const mockClaimRecords: ClaimRecord[] = [
  {
    id: generateId(),
    foodId: mockFoodItems[0].id,
    foodName: '新鲜草莓',
    department: '技术部',
    quantity: 3,
    pickupTime: hoursAgo(0.5),
    claimerName: '张三',
    createdAt: hoursAgo(0.5),
  },
  {
    id: generateId(),
    foodId: mockFoodItems[0].id,
    foodName: '新鲜草莓',
    department: '设计部',
    quantity: 2,
    pickupTime: hoursAgo(0.3),
    claimerName: '李四',
    createdAt: hoursAgo(0.3),
  },
  {
    id: generateId(),
    foodId: mockFoodItems[5].id,
    foodName: '车厘子',
    department: '产品部',
    quantity: 2,
    pickupTime: hoursAgo(1),
    claimerName: '王五',
    createdAt: hoursAgo(1),
  },
  {
    id: generateId(),
    foodId: mockFoodItems[1].id,
    foodName: '奶油蛋糕卷',
    department: '运营部',
    quantity: 4,
    pickupTime: hoursAgo(0.2),
    claimerName: '赵六',
    createdAt: hoursAgo(0.2),
  },
];

export const mockDisposalRecords: DisposalRecord[] = [
  {
    id: generateId(),
    foodId: generateId(),
    foodName: '提拉米苏',
    reason: 'expired',
    quantity: 6,
    disposedAt: hoursAgo(5),
  },
  {
    id: generateId(),
    foodId: generateId(),
    foodName: '葡萄',
    reason: 'unclaimed',
    quantity: 10,
    disposedAt: hoursAgo(8),
  },
  {
    id: generateId(),
    foodId: generateId(),
    foodName: '抹茶饼干',
    reason: 'unclaimed',
    quantity: 20,
    disposedAt: hoursAgo(12),
  },
  {
    id: generateId(),
    foodId: generateId(),
    foodName: '柠檬茶',
    reason: 'expired',
    quantity: 8,
    disposedAt: hoursAgo(6),
  },
  {
    id: generateId(),
    foodId: generateId(),
    foodName: '曲奇饼干',
    reason: 'unclaimed',
    quantity: 15,
    disposedAt: hoursAgo(20),
  },
];
