import type { Task } from '@/types';
import { generateId } from '@/utils/id';

export const SEED_TASKS: Task[] = [
  {
    id: generateId(),
    name: '公园捡树叶',
    ageRange: '4岁+',
    durationMin: 60,
    budget: 0,
    scene: 'outdoor',
    energyLevel: 'low',
    preparationItems: ['小篮子或纸袋', '放大镜', '彩色画笔'],
    steps: [
      { id: generateId(), description: '准备一个小篮子，出发去附近的公园', order: 1 },
      { id: generateId(), description: '寻找不同形状和颜色的树叶', order: 2 },
      { id: generateId(), description: '用放大镜观察树叶的脉络', order: 3 },
      { id: generateId(), description: '把捡到的树叶按颜色分类', order: 4 },
      { id: generateId(), description: '回家后用树叶做一幅拼贴画', order: 5 },
    ],
    createdAt: Date.now(),
  },
  {
    id: generateId(),
    name: '做三明治',
    ageRange: '3岁+',
    durationMin: 30,
    budget: 30,
    scene: 'indoor',
    energyLevel: 'low',
    preparationItems: ['吐司面包', '火腿/鸡胸肉', '生菜/番茄', '芝士片', '果酱/沙拉酱'],
    steps: [
      { id: generateId(), description: '洗手，准备食材和工具', order: 1 },
      { id: generateId(), description: '把生菜洗净，番茄切片', order: 2 },
      { id: generateId(), description: '在面包上涂酱料', order: 3 },
      { id: generateId(), description: '依次放上生菜、火腿、芝士、番茄', order: 4 },
      { id: generateId(), description: '盖上另一片面包，对角切开', order: 5 },
    ],
    createdAt: Date.now(),
  },
  {
    id: generateId(),
    name: '搭纸箱城堡',
    ageRange: '5岁+',
    durationMin: 90,
    budget: 20,
    scene: 'indoor',
    energyLevel: 'medium',
    preparationItems: ['大号纸箱2-3个', '剪刀/美工刀', '彩色胶带', '水彩笔/蜡笔', '旧报纸(铺地面)'],
    steps: [
      { id: generateId(), description: '在地面铺好旧报纸，把纸箱拆开', order: 1 },
      { id: generateId(), description: '设计城堡的形状，画出门窗位置', order: 2 },
      { id: generateId(), description: '大人帮忙剪出门窗', order: 3 },
      { id: generateId(), description: '用彩色胶带把纸箱拼接成城堡', order: 4 },
      { id: generateId(), description: '用水彩笔画上砖墙和装饰', order: 5 },
      { id: generateId(), description: '放几个靠垫进去，享受你的城堡！', order: 6 },
    ],
    createdAt: Date.now(),
  },
  {
    id: generateId(),
    name: '拍家庭短片',
    ageRange: '6岁+',
    durationMin: 120,
    budget: 0,
    scene: 'both',
    energyLevel: 'medium',
    preparationItems: ['手机/相机', '简单道具（帽子、围巾等）', '纸笔画分镜'],
    steps: [
      { id: generateId(), description: '一起讨论短片主题（冒险故事/搞笑日常/美食节目）', order: 1 },
      { id: generateId(), description: '用纸笔画出简单的分镜草图', order: 2 },
      { id: generateId(), description: '分配角色和准备道具', order: 3 },
      { id: generateId(), description: '按分镜拍摄各个场景', order: 4 },
      { id: generateId(), description: '用手机剪辑软件简单剪辑', order: 5 },
      { id: generateId(), description: '全家一起观看首映！', order: 6 },
    ],
    createdAt: Date.now(),
  },
  {
    id: generateId(),
    name: '去图书馆',
    ageRange: '3岁+',
    durationMin: 60,
    budget: 0,
    scene: 'indoor',
    energyLevel: 'low',
    preparationItems: ['图书馆卡（如有）', '环保袋', '小本子和笔'],
    steps: [
      { id: generateId(), description: '查看附近图书馆的开放时间', order: 1 },
      { id: generateId(), description: '到图书馆后先参观儿童阅读区', order: 2 },
      { id: generateId(), description: '每人挑选2-3本喜欢的书', order: 3 },
      { id: generateId(), description: '找个安静的角落一起阅读', order: 4 },
      { id: generateId(), description: '借几本最爱的书带回家', order: 5 },
    ],
    createdAt: Date.now(),
  },
];
