import { ParkingZone, VisitorRecord } from './types';

export const mockZones: ParkingZone[] = [
  {
    id: 'zone1',
    name: 'A区访客停车场',
    capacity: 50,
    feeRule: '首小时免费，之后5元/小时，每天封顶30元',
    feePerHour: 5,
    freeMinutes: 60,
    maxDailyFee: 30,
    visitorAvailable: true,
    entrancePhoto: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=residential%20parking%20lot%20entrance%20with%20gate%20barrier%20modern%20building&image_size=landscape_16_9',
  },
  {
    id: 'zone2',
    name: 'B区地面车位',
    capacity: 30,
    feeRule: '30分钟免费，之后8元/小时，每天封顶50元',
    feePerHour: 8,
    freeMinutes: 30,
    maxDailyFee: 50,
    visitorAvailable: true,
    entrancePhoto: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=ground%20level%20parking%20lot%20with%20marked%20spots%20residential%20area&image_size=landscape_16_9',
  },
  {
    id: 'zone3',
    name: 'C区地下车库',
    capacity: 100,
    feeRule: '业主专用，不对外开放',
    feePerHour: 0,
    freeMinutes: 0,
    maxDailyFee: 0,
    visitorAvailable: false,
  },
];

export const mockRecords: VisitorRecord[] = [
  {
    id: 'rec1',
    plateNumber: '京A12345',
    building: '3号楼',
    contactPerson: '张先生',
    phone: '13800138001',
    estimatedLeaveTime: new Date(Date.now() + 2 * 60 * 60 * 1000).toISOString(),
    zoneId: 'zone1',
    entryTime: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    paymentStatus: 'unpaid',
    isOverdue: false,
    carPhoto: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=white%20sedan%20car%20front%20view%20parking%20lot&image_size=landscape_16_9',
  },
  {
    id: 'rec2',
    plateNumber: '京B67890',
    building: '5号楼',
    contactPerson: '李女士',
    phone: '13900139002',
    estimatedLeaveTime: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    zoneId: 'zone1',
    entryTime: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    paymentStatus: 'unpaid',
    isOverdue: true,
    carPhoto: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=black%20suv%20car%20front%20view%20parking%20garage&image_size=landscape_16_9',
  },
  {
    id: 'rec3',
    plateNumber: '京C11111',
    building: '1号楼',
    contactPerson: '王先生',
    phone: '13700137003',
    estimatedLeaveTime: new Date(Date.now() + 5 * 60 * 60 * 1000).toISOString(),
    zoneId: 'zone2',
    entryTime: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    paymentStatus: 'unpaid',
    isOverdue: false,
  },
  {
    id: 'rec4',
    plateNumber: '京D22222',
    building: '8号楼',
    contactPerson: '赵先生',
    phone: '13600136004',
    estimatedLeaveTime: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    zoneId: 'zone2',
    entryTime: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    exitTime: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    actualDuration: 240,
    fee: 28,
    paymentStatus: 'paid',
    isOverdue: true,
  },
];
